name: HACS

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  validation:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master
      - name: Run HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration