name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - master
    tags:
      - "v*"

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_full_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - id: release_drafter
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          prerelease: false

      - name: Create Home Assistant release archive
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
            cd custom_components/victron_charge_control
            zip -r ${{ github.workspace }}/victron_charge_control.zip ./  

      - name: Upload release asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.release_drafter.outputs.upload_url }}
            asset_path: ${{ github.workspace }}/victron_charge_control.zip
            asset_name: victron_charge_control.zip
            asset_content_type: application/zip
  update_pre_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - id: release_drafter
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          prerelease: true
          prerelease-identifier: "rc"

      - name: Create Home Assistant release archive
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
            cd custom_components/victron_charge_control
            zip -r ${{ github.workspace }}/victron_charge_control.zip ./  

      - name: Upload release asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.release_drafter.outputs.upload_url }}
            asset_path: ${{ github.workspace }}/victron_charge_control.zip
            asset_name: victron_charge_control.zip
            asset_content_type: application/zip